# SPDX-License-Identifier: GPL-3.0-only
# Original at https://github.com/tyron12233/CodeAssist/blob/main/.github/workflows/build-apk.yml
# Changes: Minor adjustments, removal of Cancel previous runs step, but every change can be found with a simple diff.

name: Android CI[PR]

on:
  pull_request:
    paths-ignore:
      - assets/**
      - .gitignore
      - LICENCE
      - README.md

jobs:
  buildApkFile:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Allow gradlew permission
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --warning-mode all
          
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: Android Code Editor Debug Apk
          path: app/build/outputs/apk/debug
      - name: Upload editor aar debug
        uses: actions/upload-artifact@v3
        with:
          name: Editor Debug Aar
          path: editor/build/outputs/aar/editor-debug.aar